apiVersion: batch/v1
kind: Job
metadata:
  generateName: bitbucket-trigger-pipeline
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: bitbucket-trigger
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "-is -u weijenloi:$(BITBUCKET_PIPELINE)"
          - "--data-urlencode"
          - "payload={\"target\": {\"type\": \"pipeline_ref_target\", \"ref_type\": \"branch\", \"ref_name\": \"master\", \"selector\": { \"type\": \"custom\", \"pattern\": \"runtest_ces_smoke_staging\" }}}"
          - "https://api.bitbucket.org/2.0/repositories/cxplatform/ces-test/pipelines/"
      restartPolicy: Never
  backoffLimit: 0
